site_name: Documentation
docs_dir: docs
theme: readthedocs
pages:
  - Welcome: index.md
  - Introduction:
    - Framework Overview: intro/overview.md
    - Licence: intro/licence.md
  - Getting Started:
    - Requirements: getting_started/requirements.md
    - Download & Install: getting_started/install.md
    - Create an Application: getting_started/create_application.md
    - Setting Locale: getting_started/set_locale.md
    - Setting up a Web Server: 
      - Configuring Apache: getting_started/web/apache.md
      - Configuring Nginx: getting_started/web/nginx.md
  - The Basics:
    - Project Layout: basics/layout.md
    - Configuration: basics/configs.md
    - Routing: basics/routing.md
    - Controllers: basics/controllers.md
    - Views: basics/views.md
    - Models: basics/models.md
    - Bootstrap: basics/bootstrap.md
    - Generating URLs: basics/urls.md
    - Routing: basics/routing.md
    - View Helpers:
        - Overview: basics/view-helpers/overview.md
        - Textile: basics/view-helpers/textile.md
        - Custom: basics/view-helpers/custom.md
  - Advanced:
    - Authentication: advanced/authentication.md
    - Caching:
      - Overview: advanced/caching/overview.md
      - Frontends: advanced/caching/frontends.md
      - Backends: advanced/caching/backends.md
    - Filesystem Browser: advanced/filesystem_browser.md
    - Google Services: advanced/google.md
    - Less CSS: advanced/lesscss.md
    - Money: advanced/money.md
    - Multiple Class Inheritance: advanced/multiple-class-inheritance.md
    - PDF Responses: advanced/pdf.md
    - Routing Aliases: advanced/routing-aliases.md
    - Strict Models: advanced/model.md
    - The Logger: advanced/logger.md
    - WebDAV & CalDAV: advanced/dav.md
    - XMLRPC: advanced/xmlrpc.md
    - AJAX Streaming: advanced/ajax-streaming.md
    - Helper Functions: advanced/helper-functions.md
  - Administrators Guide:
    - Performance Tuning: admin/performance.md
  - Developer Reference:
    - Constants: reference/constants.md
    - Error Codes: reference/errorcodes.md
    - HTTP Status Codes: reference/http-status-codes.md
  - A Simple Tutorial: 
    - What do you need?: tutorial/what-do-you-need.md
    - Your First Hazaar App: tutorial/your-first-app.md
    - Something Useful: tutorial/something-useful.md
    - Creating Responses: tutorial/responses.md
    - What's Next: tutorial/next.md
markdown_extensions:
    - admonition
